# Generated by Django 4.2.3 on 2024-09-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0003_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="Default.png", upload_to="media/", verbose_name="image"
            ),
        ),
    ]
